fix(treewide): use newer rtc-node version
a new version of rtc-node is incompatible with previous releases, and
will lead to Rust panics if two or more differing versions are used
between packages:

```
thread '<unnamed>' panicked at src/nodejs.rs:52:13:
failed to handle request: invalid request: handle not found
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
```

this patch updates agents repositories to the latest version of
rtc-node, so it should be okay to use the latest available version on
your end as well.

if for some reason you can't update agents, pin the version of
`@livekit/rtc-node` to `=0.9.0`.